[build]
  command = "npm install && npm run build"
  functions = "netlify/functions"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/delhi-advanced.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 8080
  publish = "."
  autoLaunch = false
